### ISSUE TITLE
Suggestion for cleaning up the working baseline doc

### ISSUE THREAD

**Issue by hartig** [w3c/rdf-star-wg#126]
@franconi Looking at the current version of https://github.com/w3c/rdf-star-wg/wiki/RDF-star-%22working-baseline%22 I notice:
1. The first grammar ("ABSTRACT SYNTAX") contains a production called `atomicTerm` which is not used anywhere else in the grammar.
2. The sentence that introduces the function `[I+A](.)` in the SIMPLE SEMANTICS section also introduces a function `[[I+A]](.)` which is not actually defined or used anywhere in the document.

I assume that both of these are artifacts of earlier versions of the doc and propose to remove them in order to avoid confusion. Do you agree?

**Comment by franconi** [comment]
On 16 Aug 2024, at 12:41, Olaf Hartig ***@***.***> wrote:



@franconi<https://github.com/franconi> Looking at the current version of https://github.com/w3c/rdf-star-wg/wiki/RDF-star-%22working-baseline%22 I notice:

  1.  The first grammar ("ABSTRACT SYNTAX") contains a production called atomicTerm which is not used anywhere else in the grammar.

This has been introduced in order to be able to discuss about atomic terms in RDF Concepts ar anywhere else where it could be useful to identify the RDF 1.1 fragment of RDF 1.2. Feel free to drop it if it is not useful for this purpose.


  1.  The sentence that introduces the function [I+A](.) in the SIMPLE SEMANTICS section also introduces a function [[I+A]](.) which is not actually defined or used anywhere in the document.

It is a witness of a former version of the baseline with opaque IRIs.

I assume that both of these are artifacts of earlier versions of the doc and propose to remove them in order to avoid confusion. Do you agree?

Yes. Note that I maintain a working evolved version of the baseline, where these fixes are implemented:

https://github.com/w3c/rdf-star-wg/wiki/RDF-star-"working-baseline"

cheers
—e.

**Comment by hartig** [comment]
> Yes. Note that I maintain a working evolved version of the baseline, where these fixes are implemented:
>
> https://github.com/w3c/rdf-star-wg/wiki/RDF-star-"working-baseline"

That's exactly the version that I was referring to (URL-encoded link: https://github.com/w3c/rdf-star-wg/wiki/RDF-star-%22working-baseline%22).

Thanks for removing `[[I+A]](.)`.

I have now also removed the unused `atomicTerm` production from the grammar, aiming to keep only the things that are essential to understanding the baseline approach.
