### ISSUE TITLE
make w3c/rdf-tests a joint repo of the RDF-tests CG and the RDF-star WG

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg#77]
see https://www.w3.org/2023/07/13-rdf-star-minutes.html#t05
and https://lists.w3.org/Archives/Public/public-rdf-tests/2023Jul/0000.html

**Comment by gkellogg** [comment]
I had the permissions to add https://github.com/orgs/w3c/teams/rdf-star-editors to have Triage access to https://github.com/w3c/rdf-tests, which will allow people in that group to review and otherwise contribute to the repo. There is a https://github.com/orgs/w3c/teams/rdf-tests-contributors which we can add anyone to who need Write access.
