### ISSUE TITLE
ambiguity of canonical N-Triples

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg#9]
The [specification of canonical N-Triples](https://www.w3.org/TR/n-triples/#canonical-ntriples) is silent about the datatype of `xsd:string` literals. More specifically :
```
    "hello world"
```
and
```
   "hello world"^^<http://www.w3.org/2001/XMLSchema#string>
```
are equivalent terms in N-Triples and N-Quads, and the spec does not say which one should be used as the canonical form.

This has an impact on the RCH working group (https://github.com/w3c/rdf-canon/issues/66).

**Comment by pchampin** [comment]
We may want to add this to https://www.w3.org/2001/sw/wiki/RDF1.1_Errata

**Comment by Tpt** [comment]
It seems to be an other element of the erratum 32 "Issues with N-Quads/N-Triples canonicalization"

**Comment by TallTed** [comment]
@Tpt —

I think this issue is different enough from what is now discussed in Erratum 32 ([report](https://www.w3.org/mid/A5E7D9F6-CA8C-4C10-A567-C2FB14BA297A@greggkellogg.net), [reply_1](https://www.w3.org/mid/2A8D0EB8-AC76-442D-8DAF-F132D07AA311@evilfunhouse.com), [followup_1](https://www.w3.org/mid/A5E7D9F6-CA8C-4C10-A567-C2FB14BA297A@greggkellogg.net)) to warrant its own entry in the errata list.

(I might also suggest that @afs split the current Erratum 32 from the ultra-generic "Issues with N-Quads/N-Triples canonicalization" into 2 errata, one each for the (a) technical and (b) editorial issues contained in the initial report, with more specific descriptions for each.)

**Comment by afs** [comment]
@TallTed
@pchampin 

It's a wiki! You can edit it.

Adding errata and raising issues here is double accounting. I personally would prefer that the errata became issues when we have the doc repos strategy decided and running.

**Comment by TallTed** [comment]
Double-entry bookkeeping is helpful in many arenas, and I think this is one such.

I think it's also useful to have an issue for each erratum on the relevant doc(s) repo(s), as soon as practicable, existence and resolution of which should be accessible via whatever errata summary list we maintain.

Regarding which, I think the errata wiki page provides a useful living summary update which will remain useful until we issue FPWD and/or CR, and possibly even until PR, of all docs mentioned therein.  The wiki page content *could* be replaced with a link to a tracking issue, wherein we keep a list of all errata issues, to be created from existing errata list(s) and any new errata that surface as we go, but I think this is less wieldy for this purpose than the wiki page.

**Comment by pchampin** [comment]
just added this one as https://www.w3.org/2001/sw/wiki/RDF1.1_Errata#erratum_33

**Comment by gkellogg** [comment]
I think this is resolved now, and can be closed.
